-- liquibase formatted sql

-- changeset andrey:createFavorites
CREATE TABLE Favorites (
FavoriteID INT AUTO_INCREMENT NOT NULL,
UserID INT NOT NULL,
ProductID INT NOT NULL,
CONSTRAINT PK_FAVORITES PRIMARY KEY (FavoriteID));

-- changeset andrey:IndexFavoritesToUserFk
CREATE INDEX FK_FAVORITES_USERID_IDX ON Favorites(UserID);

-- changeset andrey:REFERENCES_Favorite_UserId
ALTER TABLE Favorites ADD CONSTRAINT FK_FAVORITES_USERID_REFERENCES FOREIGN KEY (UserID) REFERENCES Users (UserID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset andrey:IndexFavoritesToProductFk
CREATE INDEX FK_FAVORITES_PRODUCTID_IDX ON Favorites(ProductID);

-- changeset andrey:REFERENCES_Favorites_ProductId
ALTER TABLE Favorites ADD CONSTRAINT FK_FAVORITES_PRODUCTID_REFERENCES FOREIGN KEY (ProductID) REFERENCES Products (ProductID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset andrey:createCart
CREATE TABLE Cart (
CartID INT AUTO_INCREMENT NOT NULL,
UserID INT NOT NULL,
CONSTRAINT PK_CART PRIMARY KEY (CartID));

-- changeset andrey:IndexCartToUserFk
CREATE INDEX FK_CART_USERID_IDX ON Cart(UserID);

-- changeset andrey:REFERENCES_Cart_UserId
ALTER TABLE Cart ADD CONSTRAINT FK_CART_USERID_REFERENCES FOREIGN KEY (UserID) REFERENCES Users (UserID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset andrey:createCartItems
CREATE TABLE CartItems (
CartItemID INT AUTO_INCREMENT NOT NULL,
CartID INT NOT NULL,
ProductID INT NOT NULL,
Quantity INT NOT NULL,
CONSTRAINT PK_CARTITEMID PRIMARY KEY (CartItemID));

-- changeset andrey:IndexCartItemIdToCart
CREATE INDEX FK_CARTITEMID_CART_IDX ON CartItems(CartID);

-- changeset andrey:REFERENCES_CartItems_CartId
ALTER TABLE CartItems ADD CONSTRAINT FK_CARTITEMS_CARTID_REFERENCES FOREIGN KEY (CartID) REFERENCES Cart (CartID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset andrey:IndexCartItemIdToProduct
CREATE INDEX FK_CARTITEMID_PRODUCT_IDX ON CartItems(ProductID);

-- changeset andrey:REFERENCES_CartItems_ProductId
ALTER TABLE CartItems ADD CONSTRAINT FK_CARTITEMS_PRODUCTID_REFERENCES FOREIGN KEY (ProductID) REFERENCES Products (ProductID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset andrey:createOrders
CREATE TABLE Orders (
OrderID INT AUTO_INCREMENT NOT NULL,
UserID INT NOT NULL,
CreatedAt TIMESTAMP NOT NULL,
DeliveryAddress VARCHAR(255) NOT NULL,
ContactPhone VARCHAR(255) NOT NULL,
DeliveryMethod VARCHAR(16) NOT NULL,
Status VARCHAR(16) NOT NULL,
UpdatedAt TIMESTAMP,
CONSTRAINT PK_ORDERID PRIMARY KEY (OrderID));

-- changeset andrey:IndexOrdersToUser
CREATE INDEX FK_ORDERS_USER_IDX ON Orders(UserID);

-- changeset andrey:REFERENCES_Orders_UserId
ALTER TABLE Orders ADD CONSTRAINT FK_ORDERS_USER_REFERENCES FOREIGN KEY (UserID) REFERENCES Users (UserID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset andrey:createOrderItems
CREATE TABLE OrderItems (
OrderItemID INT AUTO_INCREMENT NOT NULL,
OrderID INT NOT NULL,
ProductID INT NOT NULL,
Quantity INT NOT NULL,
PriceAtPurchase DOUBLE NOT NULL,
CONSTRAINT PK_ORDERITEMID PRIMARY KEY (OrderItemID));

-- changeset andrey:IndexOrderItemsToOrder
CREATE INDEX FK_ORDERITEMS_ORDERS_IDX ON OrderItems(OrderID);

-- changeset andrey:REFERENCES_OrderItems_OrderId
ALTER TABLE OrderItems ADD CONSTRAINT FK_ORDERITEMS_ORDERS_REFERENCES FOREIGN KEY (OrderID) REFERENCES Orders (OrderID) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- changeset andrey:IndexOrderItemsToProducts
CREATE INDEX FK_ORDERITEMS_PRODUCTS_IDX ON OrderItems(ProductID);

-- changeset andrey:REFERENCES_OrderItems_ProductId
ALTER TABLE OrderItems ADD CONSTRAINT FK_ORDERITEMS_PRODUCTS_REFERENCES FOREIGN KEY (ProductID) REFERENCES Products (ProductID) ON UPDATE RESTRICT ON DELETE RESTRICT;


